// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9dyZtqzTIelVR1_FR2qZDpgpaHsZg4w',
    appId: '1:206545865491:web:cf888548304e32d37328e6',
    messagingSenderId: '206545865491',
    projectId: 'notecraft-cheoo',
    authDomain: 'notecraft-cheoo.firebaseapp.com',
    storageBucket: 'notecraft-cheoo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0WOh9OGsZbjKt07D4-xd3cvfPuCoLiY',
    appId: '1:206545865491:android:09d3d0f4053f4fd07328e6',
    messagingSenderId: '206545865491',
    projectId: 'notecraft-cheoo',
    storageBucket: 'notecraft-cheoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLZ1hM8UnAjzwJUCpFq1sIMiiZmYzi_8',
    appId: '1:206545865491:ios:44351294adafe78d7328e6',
    messagingSenderId: '206545865491',
    projectId: 'notecraft-cheoo',
    storageBucket: 'notecraft-cheoo.firebasestorage.app',
    iosBundleId: 'com.example.notecraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLZ1hM8UnAjzwJUCpFq1sIMiiZmYzi_8',
    appId: '1:206545865491:ios:44351294adafe78d7328e6',
    messagingSenderId: '206545865491',
    projectId: 'notecraft-cheoo',
    storageBucket: 'notecraft-cheoo.firebasestorage.app',
    iosBundleId: 'com.example.notecraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb9dyZtqzTIelVR1_FR2qZDpgpaHsZg4w',
    appId: '1:206545865491:web:63e96c93fcc24c047328e6',
    messagingSenderId: '206545865491',
    projectId: 'notecraft-cheoo',
    authDomain: 'notecraft-cheoo.firebaseapp.com',
    storageBucket: 'notecraft-cheoo.firebasestorage.app',
  );
}
